remove this

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -39,8 +39,7 @@ on:
         type: boolean
         default: false
 env:
-  PULL_IMAGE_REGISTRY: ghcr.io/ublue-os
-  PUSH_IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
+  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
@@ -103,12 +102,12 @@ jobs:
         run: |
           echo "SHA_HEAD_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
 
-      - name: Verify main image
-        uses: EyeCantCU/cosign-action/verify@v0.3.0
-        with:
-          containers: ${{ matrix.base_image_name }}-${{ matrix.base_image_flavor }}:${{ matrix.fedora_version }}
-          pubkey: https://raw.githubusercontent.com/ublue-os/${{ matrix.base_image_flavor }}/main/cosign.pub
-          registry: ${{ env.PULL_IMAGE_REGISTRY }}
+      # - name: Verify main image
+      #   uses: EyeCantCU/cosign-action/verify@v0.3.0
+      #   with:
+      #     containers: ${{ matrix.base_image_name }}-${{ matrix.base_image_flavor }}:${{ matrix.fedora_version }}
+      #     pubkey: https://raw.githubusercontent.com/ublue-os/${{ matrix.base_image_flavor }}/main/cosign.pub
+      #     registry: ${{ env.PULL_IMAGE_REGISTRY }}
 
       # TODO BML make kernel img verifiable
       # - name: Verify akmods-nvidia image
@@ -145,28 +144,28 @@ jobs:
           command: |
             # pull the base images used for FROM in Containerfile so
             # we can retry on that unfortunately common failure case
-            sudo podman pull ${{ env.PULL_IMAGE_REGISTRY }}/${{ matrix.base_image_name }}-${{ matrix.base_image_flavor }}:${{ matrix.fedora_version }}
-            sudo podman pull ${{ env.PULL_IMAGE_REGISTRY }}/drelbsos-kernel:${{ matrix.fedora_version }}
+            # sudo podman pull ${{ env.IMAGE_REGISTRY }}/${{ matrix.base_image_name }}-${{ matrix.base_image_flavor }}:${{ matrix.fedora_version }}
+            sudo podman pull ${{ env.IMAGE_REGISTRY }}/drelbsos-kernel:${{ matrix.fedora_version }}
 
             # Add rechunk as well to remove this source of failure
             sudo podman pull ghcr.io/hhd-dev/rechunk:v1.2.1
 
-      - name: Get source versions
-        id: labels
-        uses: Wandalen/wretry.action@v3.8.0
-        with:
-          attempt_limit: 3
-          attempt_delay: 15000
-          command: |
-            set -eo pipefail
-            skopeo inspect docker://${{ env.PULL_IMAGE_REGISTRY }}/${{ matrix.base_image_name }}-${{ matrix.base_image_flavor }}:${{ matrix.fedora_version }} > source.json
-            ver=$(jq -r '.Labels["org.opencontainers.image.version"]' source.json)
-            if [ -z "$ver" ] || [ "null" = "$ver" ]; then
-              echo "inspected image version must not be empty or null"
-              exit 1
-            fi
-            echo "SOURCE_IMAGE_VERSION=$ver" >> $GITHUB_ENV
-      
+      # - name: Get source versions
+      #   id: labels
+      #   uses: Wandalen/wretry.action@v3.8.0
+      #   with:
+      #     attempt_limit: 3
+      #     attempt_delay: 15000
+      #     command: |
+      #       set -eo pipefail
+      #       skopeo inspect docker://${{ env.PULL_IMAGE_REGISTRY }}/${{ matrix.base_image_name }}-${{ matrix.base_image_flavor }}:${{ matrix.fedora_version }} > source.json
+      #       ver=$(jq -r '.Labels["org.opencontainers.image.version"]' source.json)
+      #       if [ -z "$ver" ] || [ "null" = "$ver" ]; then
+      #         echo "inspected image version must not be empty or null"
+      #         exit 1
+      #       fi
+      #       echo "SOURCE_IMAGE_VERSION=$ver" >> $GITHUB_ENV
+
       # Generate a primary version key that appears
       # in KDE, rpm-ostree status, and github.
       - name: Generate Version
@@ -222,8 +221,8 @@ jobs:
       - name: Remove auxiliary images
         # We are tight on space, need at least 2x for OSTree
         run: |
-          sudo podman image rm ${{ env.PULL_IMAGE_REGISTRY }}/${{ matrix.base_image_name }}-${{ matrix.base_image_flavor }}:${{ matrix.fedora_version }}
-          sudo podman image rm ${{ env.PULL_IMAGE_REGISTRY }}/drelbsos-kernel:${{ matrix.fedora_version }}
+          # sudo podman image rm ${{ env.PULL_IMAGE_REGISTRY }}/${{ matrix.base_image_name }}-${{ matrix.base_image_flavor }}:${{ matrix.fedora_version }}
+          sudo podman image rm ${{ env.IMAGE_REGISTRY }}/drelbsos-kernel:${{ matrix.fedora_version }}
 
       # Generate the previous image reference used by the Rechunker
       - name: Generate previous reference
